/**
 * env-registry.ts — RIVET_* 环境变量注册表（自动生成）。
 *
 * name/defaultHint/files 由 scripts/gen-env-registry.ts 生成，勿手改；
 * description 字段人工维护，重新生成时按 name 保留。
 * 最后生成：2026-09-11T02:34:09.294Z
 * 共 165 个变量。
 *
 * 每个条目含：名称 / 默认值提示 / 引用文件 / 简要说明。
 * 当源码中新增 RIVET_* 引用但注册表未同步时，
 * assembly-audit.test.ts 的 env completeness 测试会失败（双向检查）。
 */

export interface EnvRegistryEntry {
  /** 环境变量名（含 RIVET_ 前缀） */
  name: string
  /** 从源码 ??/|| 推断的默认值，若无则为空 */
  defaultHint: string
  /** 引用该变量的源文件列表（相对 src/） */
  files: string[]
  /** 简要说明（人工维护，重新生成时保留） */
  description: string
}

export const ENV_REGISTRY: EnvRegistryEntry[] = [
  {
    name: 'RIVET_ADAPTIVE_MEMORY',
    defaultHint: '',
    files: ['memory/adaptive-stm.ts'],
    description: '意图门控 STM：shadow 仅评估不注入；on/1 经 appendixDelta 注入；off/0 关闭。',
  },
  {
    name: 'RIVET_ADVISORY_EFFICACY_SPAN',
    defaultHint: '',
    files: ['agent/advisory-bus.ts', 'agent/__tests__/advisory-efficacy-sort.test.ts'],
    description: '效力对 advisory 有效优先级的最大调整幅度（±），0 关闭效力排序',
  },
  {
    name: 'RIVET_ADVISORY_HOLDOUT',
    defaultHint: '',
    files: ['agent/loop.ts'],
    description: 'advisory holdout 对照组开关（P1a 核销闭环）',
  },
  {
    name: 'RIVET_ADVISORY_LIFT_CONSUMER',
    defaultHint: '',
    files: ['agent/loop.ts'],
    description: '',
  },
  {
    name: 'RIVET_AMBIGUOUS_WIDTH',
    defaultHint: '\'\'',
    files: ['tui/width.ts', 'tui/engine/__tests__/live-engine-ghost-render.test.ts', 'tui/__tests__/width.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_AMNESIA_SHADOW',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_APPENDIX_TRACE',
    defaultHint: '',
    files: ['agent/appendix-trace.ts', 'agent/__tests__/appendix-trace.test.ts'],
    description: '设为 1 把逐请求的附录渲染结果落到 <会话目录>/appendix-trace.jsonl（默认关；自述层此前零留痕，事后无法取一份模型真实看到的块）',
  },
  {
    name: 'RIVET_APPLY_PATCH_VERIFY',
    defaultHint: '',
    files: ['tools/apply-patch.ts'],
    description: '',
  },
  {
    name: 'RIVET_APPROVAL_TIMEOUT_MS',
    defaultHint: '',
    files: ['server/session-manager.ts'],
    description: '',
  },
  {
    name: 'RIVET_ASCII_UI',
    defaultHint: '',
    files: ['tui/term-caps.ts', 'tui/format/__tests__/side-question.test.ts', 'tui/engine/__tests__/app-core.test.ts', 'tui/__tests__/format-plan-picker.test.ts', 'tui/__tests__/format-welcome.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_AST_EDIT_VERIFY',
    defaultHint: '',
    files: ['tools/ast-edit.ts'],
    description: '',
  },
  {
    name: 'RIVET_AST_EXCLUDE',
    defaultHint: '',
    files: ['tools/ast-shared.ts', 'tools/__tests__/ast-shared.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_AST_SCAN_TIMEOUT_MS',
    defaultHint: '',
    files: ['tools/ast-shared.ts', 'tools/__tests__/ast-edit.test.ts', 'tools/__tests__/ast-grep.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_ASYNC_COPILOT',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_BROWSER_ALLOWLIST',
    defaultHint: '\'\'',
    files: ['tools/browser.ts', 'tools/browser-debug/tool.ts'],
    description: '',
  },
  {
    name: 'RIVET_BROWSER_DEBUG',
    defaultHint: '',
    files: ['bootstrap.ts'],
    description: '',
  },
  {
    name: 'RIVET_BROWSER_URL',
    defaultHint: '',
    files: ['tools/browser-debug/tool.ts'],
    description: '',
  },
  {
    name: 'RIVET_BUNDLED_PLUGINS_DIR',
    defaultHint: '',
    files: ['server/plugin-api.ts', 'server/__tests__/plugin-api.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_BUNDLED_RIPGREP_DIR',
    defaultHint: '',
    files: ['tools/grep.ts'],
    description: '',
  },
  {
    name: 'RIVET_BUNDLED_SKILLS_DIR',
    defaultHint: '',
    files: ['skills/skill-loader.ts'],
    description: '',
  },
  {
    name: 'RIVET_CANCEL_REST',
    defaultHint: '',
    files: ['agent/batch-short-circuit.ts', 'agent/__tests__/batch-short-circuit.test.ts'],
    description: 'delegateBatch 聚合策略（first_success/quorum）中途达标后短路取消剩余兄弟 worker，默认开；设 0/false/off/no 关闭',
  },
  {
    name: 'RIVET_CAPABILITY',
    defaultHint: '',
    files: ['tools/default-registry.ts', 'tools/__tests__/tool-preset.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_CLAIM_AUDIT',
    defaultHint: '',
    files: ['agent/claim-audit.ts', 'agent/__tests__/claim-audit.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_CLI_DISCOVER',
    defaultHint: '',
    files: ['tools/default-registry.ts'],
    description: '',
  },
  {
    name: 'RIVET_COMPUTER_USE',
    defaultHint: '',
    files: ['bootstrap.ts', 'main.ts', 'server/config-routes.ts'],
    description: '',
  },
  {
    name: 'RIVET_COMPUTER_USE_AUTOMOUNT',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_CONFIG_PATH',
    defaultHint: '',
    files: ['tui/__tests__/settings-persist.test.ts', 'tui/__tests__/slash-commands.test.ts', 'tools/__tests__/tool-preset.test.ts', 'server/__tests__/vision-model-onboarding-routes.test.ts', 'plugins/__tests__/integration/git-source-mirror-fallback.test.ts', 'config/paths.ts', 'config/__tests__/config-cli.test.ts', 'config/__tests__/config-load-error.test.ts', 'config/__tests__/config-schema-integration.test.ts', 'config/__tests__/config-watcher.test.ts', 'config/__tests__/layered-config.test.ts', 'config/__tests__/manager-clear-api-key.test.ts', 'config/__tests__/manager-editor.test.ts', 'config/__tests__/manager-fetch-search.test.ts', 'config/__tests__/manager-permission-dirs.test.ts', 'config/__tests__/manager-provider.test.ts', 'config/__tests__/manager-routing.test.ts', 'config/__tests__/manager-shell.test.ts', 'config/__tests__/manager-ui.test.ts', 'config/__tests__/manager-vision-model.test.ts', 'config/__tests__/preset-model-backfill.test.ts', 'config/__tests__/provider-advanced.test.ts', 'config/__tests__/provider-cli.test.ts', 'config/__tests__/provider-onboarding-e2e.test.ts', 'config/__tests__/runtime-lean-aspect.test.ts', 'config/__tests__/runtime-lean.test.ts', 'config/__tests__/secrets-store.test.ts', '__tests__/bootstrap.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_CONFIG_WATCH',
    defaultHint: '',
    files: ['config/config-watcher.ts', 'config/__tests__/config-watcher.test.ts'],
    description: '=0 关闭 config HMR 热更（config-watcher 不 watch 配置文件）',
  },
  {
    name: 'RIVET_CONTROL_PLANE',
    defaultHint: '',
    files: ['agent/control-plane-adapters.ts'],
    description: '',
  },
  {
    name: 'RIVET_CPU_POOL',
    defaultHint: '',
    files: ['workers/cpu-pool.ts', 'workers/__tests__/cpu-pool.test.ts', 'server/__tests__/disable-cpu-pool.ts'],
    description: '',
  },
  {
    name: 'RIVET_CPU_POOL_IDLE_MS',
    defaultHint: '',
    files: ['workers/cpu-pool.ts'],
    description: '',
  },
  {
    name: 'RIVET_CROSS_SESSION_INJECT',
    defaultHint: '',
    files: ['agent/cross-session-memory-config.ts', 'agent/__tests__/cross-session-killswitch.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_CVM_VECTOR',
    defaultHint: '',
    files: ['agent/hooks/cognitive-capsule-router.ts'],
    description: '',
  },
  {
    name: 'RIVET_DEAD_END_DETECTOR',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_DEBUG',
    defaultHint: '',
    files: ['utils/debug.ts', 'tui/engine/__tests__/image-tool.test.ts', 'api/__tests__/openai-client-tool-stream-log.test.ts', 'agent/__tests__/deliver-task.test.ts', 'agent/__tests__/tool-pipeline.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_DEBUG_ORPHAN',
    defaultHint: '',
    files: ['context/resume-preflight.ts'],
    description: '',
  },
  {
    name: 'RIVET_DEBUG_RAW_SSE',
    defaultHint: '',
    files: ['api/openai-client.ts'],
    description: '',
  },
  {
    name: 'RIVET_DEBUG_RENDER',
    defaultHint: '',
    files: ['server/session-routes.ts'],
    description: '',
  },
  {
    name: 'RIVET_DEBUG_TELEMETRY',
    defaultHint: '',
    files: ['tui/engine/perf-monitor.ts'],
    description: '',
  },
  {
    name: 'RIVET_DEBUG_TOOL_INPUT',
    defaultHint: '',
    files: ['agent/tool-pipeline.ts', 'agent/__tests__/tool-pipeline.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_DEBUG_TOOL_STREAM',
    defaultHint: '',
    files: ['api/openai-client.ts'],
    description: '',
  },
  {
    name: 'RIVET_DECISIONS_INJECT',
    defaultHint: '',
    files: ['agent/decisions-experiment.ts'],
    description: 'decisions 通道注入：默认/0 关，1 强制开（确定性复现用），experiment 按会话 90/10 分组跑 holdout 实验。该分支曾因 session-state 空壳恒真而不可达，开启是未度量的行为变更，退出阈值见 decisions-experiment.ts',
  },
  {
    name: 'RIVET_DESKTOP',
    defaultHint: '',
    files: ['config/pro-license.ts', 'config/__tests__/pro-license.test.ts'],
    description: '由桌面端 Tauri 注入（CLI 无此变量），Pro 授权判定的分流开关：置位走桌面硬 gate（只认同样由 Rust 注入的 RIVET_PRO），缺席走 CLI 软 gate（config > env > file 三路径）',
  },
  {
    name: 'RIVET_DESKTOP_DIR',
    defaultHint: 'join(rivetHome(',
    files: ['config/paths.ts'],
    description: '',
  },
  {
    name: 'RIVET_DESKTOP_SESSION_DIR',
    defaultHint: 'join(desktopDir(',
    files: ['config/paths.ts'],
    description: '',
  },
  {
    name: 'RIVET_EDIT_SMART_ROUTING',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_EMBEDDING_API_KEY',
    defaultHint: 'env.DEEPSEEK_API_KEY',
    files: ['search/embedding-provider.ts'],
    description: '',
  },
  {
    name: 'RIVET_EMBEDDING_BASE_URL',
    defaultHint: '(env.OPENAI_API_KEY ? \'https://api.opena',
    files: ['search/embedding-provider.ts'],
    description: '',
  },
  {
    name: 'RIVET_EMBEDDING_MODEL',
    defaultHint: '\'text-embedding-3-small\'',
    files: ['search/embedding-provider.ts'],
    description: '',
  },
  {
    name: 'RIVET_EMBEDDING_TIMEOUT',
    defaultHint: '\'\'',
    files: ['search/embedding-provider.ts'],
    description: '',
  },
  {
    name: 'RIVET_ESBUILD_LOAD_TIMEOUT',
    defaultHint: '\'\'',
    files: ['tools/syntax-check.ts', 'tools/__tests__/syntax-check.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_EXTERNAL_CLAIM_TRACKING',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts', 'agent/__tests__/create-runtime-hooks.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_FETCH_PIN',
    defaultHint: '',
    files: ['tools/net/http-fetch.ts'],
    description: '',
  },
  {
    name: 'RIVET_FETCH_PLAYWRIGHT',
    defaultHint: '',
    files: ['tools/web-fetch/build-options.ts'],
    description: '',
  },
  {
    name: 'RIVET_FETCH_SKIP_COMPILE',
    defaultHint: '\'unset\'',
    files: ['repo/__tests__/native-resolver.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_FORCE_RECOVERY_CLI',
    defaultHint: '',
    files: ['main.ts'],
    description: '',
  },
  {
    name: 'RIVET_GATE_BLOCK_GUARD',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_GENERAL_LEDGER_REMINDER',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_GIT_CLEAR_GUARD',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_GOAL_PLAN_AUTO_APPROVE_MS',
    defaultHint: '',
    files: ['tui/plan-auto-approve.ts', 'server/serve.ts'],
    description: '',
  },
  {
    name: 'RIVET_HEADLESS_MAX_TURNS',
    defaultHint: '',
    files: ['main.ts'],
    description: '非 goal 模式下 -p 一次提示的最大轮数（默认 15）；benchmark/eval 多文档任务可调高',
  },
  {
    name: 'RIVET_HOME',
    defaultHint: '',
    files: ['tui/engine/__tests__/connect-draft-engine.test.ts', 'tui/engine/__tests__/connect-wizard-list.test.ts', 'tui/engine/__tests__/overlay-deactivate-regression.test.ts', 'tui/__tests__/history-async.test.ts', 'tui/__tests__/updater.test.ts', 'tools/__tests__/tool-preset.test.ts', 'server/__tests__/config-routes.test.ts', 'server/__tests__/mcp-hot-add.test.ts', 'server/__tests__/mcp-inject-tools.test.ts', 'server/__tests__/mcp-server-config.test.ts', 'server/__tests__/path-grants-routes.test.ts', 'server/__tests__/plugin-api.test.ts', 'server/__tests__/project-docs-routes.test.ts', 'server/__tests__/serve-switch-model.test.ts', 'server/__tests__/session-manager.test.ts', 'server/__tests__/session-routes.test.ts', 'server/__tests__/trust-api.test.ts', 'server/__tests__/worker-log-route.test.ts', 'prompt/__tests__/block-policy.test.ts', 'plugins/__tests__/design-plugin-lib.test.ts', 'plugins/__tests__/plugin-installer.test.ts', 'plugins/__tests__/plugin-loader.test.ts', 'mcp/oauth/__tests__/connector.test.ts', 'config/paths.ts', 'config/__tests__/config-cli.test.ts', 'config/__tests__/config-watcher.test.ts', 'config/__tests__/profile.test.ts', 'config/__tests__/project-trust.test.ts', 'config/__tests__/remove-model.test.ts', 'cli/__tests__/prompt-version-warning.test.ts', 'auth/__tests__/login-flow.test.ts', 'api/deepseek-platform-client.ts', 'agent/__tests__/session-cd.test.ts', 'agent/__tests__/worker-session.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_HOOKS_DISABLED',
    defaultHint: '',
    files: ['config/profile.ts', 'agent/__tests__/loop-factory.test.ts'],
    description: '逗号分隔的 CVM 管线禁用 hook id 列表，优先于 config.hooks.disabled（热更见 config-watcher）',
  },
  {
    name: 'RIVET_HYPERLINKS',
    defaultHint: '',
    files: ['tui/engine/ansi.ts'],
    description: '',
  },
  {
    name: 'RIVET_IMAGES',
    defaultHint: '',
    files: ['tui/engine/ansi.ts'],
    description: '',
  },
  {
    name: 'RIVET_IMPORT_RESOURCE',
    defaultHint: '',
    files: ['tools/default-registry.ts', 'tools/__tests__/tool-preset.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_INTENT_ANCHOR',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_INTENT_ANCHOR_STALE',
    defaultHint: '',
    files: ['agent/hooks/__tests__/intent-anchor-hook.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_INTENT_ANCHOR_TURNS',
    defaultHint: '',
    files: ['agent/hooks/__tests__/intent-anchor-hook.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_JOB_MAX_MS',
    defaultHint: '\'\'',
    files: ['tools/job-store.ts'],
    description: '',
  },
  {
    name: 'RIVET_LANGUAGE_ANCHOR',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_LEAN',
    defaultHint: '',
    files: ['repo/__tests__/meridian-backfill.test.ts', 'config/runtime-lean.ts', 'config/__tests__/runtime-lean-aspect.test.ts', 'config/__tests__/runtime-lean.test.ts'],
    description: 'Runtime lean profile (minimal tools, lean prompt, no embeddings, no Meridian startup backfill, tighter session pool).',
  },
  {
    name: 'RIVET_LEAN_ASPECT',
    defaultHint: '',
    files: ['config/runtime-lean.ts', 'config/__tests__/runtime-lean-aspect.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_LEAN_AUTO',
    defaultHint: '',
    files: ['config/__tests__/runtime-lean.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_LEAVE_MARK',
    defaultHint: '',
    files: ['tools/default-registry.ts'],
    description: '',
  },
  {
    name: 'RIVET_MAX_EVENTS',
    defaultHint: '',
    files: ['server/session-manager.ts', 'server/__tests__/session-history-page.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_MCP_LOG_BYTES',
    defaultHint: '\'\'',
    files: ['mcp/log-buffer.ts', 'mcp/__tests__/log-buffer.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_MCP_OAUTH_CLIENT_ID',
    defaultHint: '\'\'',
    files: ['tui/slash-commands.ts', 'mcp/manager.ts'],
    description: '',
  },
  {
    name: 'RIVET_MCP_RECONNECT',
    defaultHint: '',
    files: ['mcp/manager.ts'],
    description: '',
  },
  {
    name: 'RIVET_MEMORY_AUTO_CAPTURE',
    defaultHint: '',
    files: ['memory/auto-capture.ts'],
    description: '记忆形成侧：重要操作后模型判断并写入 LTM；off/0 关闭，默认开启。',
  },
  {
    name: 'RIVET_MEMORY_BACKFILL',
    defaultHint: '',
    files: ['memory/backfill.ts'],
    description: '历史会话回填（opt-in）：启动 30s 后闲时补采存量会话的知识写 LTM（ledger 幂等，每轮 ≤5 会话）；1/on 开启，默认关闭。',
  },
  {
    name: 'RIVET_MEMORY_CONSOLIDATION',
    defaultHint: '',
    files: ['memory/session-consolidation.ts'],
    description: '会话结束巩固：生成会话摘要 + 可复用做法写入 LTM；off/0 关闭，默认开启。',
  },
  {
    name: 'RIVET_MEMORY_LIMIT_BYTES',
    defaultHint: '',
    files: ['agent/resource-sensor.ts', 'agent/__tests__/resource-sensor.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_MERIDIAN_BACKFILL',
    defaultHint: '',
    files: ['tools/__tests__/repo-graph-flow.test.ts', 'repo/meridian-backfill.ts', 'repo/__tests__/meridian-backfill.test.ts'],
    description: 'Meridian 后台全量索引总开关，设 0 整体关闭（默认开）',
  },
  {
    name: 'RIVET_MERIDIAN_BACKFILL_MAX',
    defaultHint: '',
    files: ['repo/meridian-backfill.ts', 'repo/__tests__/meridian-backfill.test.ts'],
    description: 'Meridian 后台全量索引的文件数上限（默认 2000）',
  },
  {
    name: 'RIVET_NEW_SESSION',
    defaultHint: '',
    files: ['bootstrap.ts', 'main.ts'],
    description: '',
  },
  {
    name: 'RIVET_NO_AUTO_RESUME',
    defaultHint: '',
    files: ['bootstrap.ts'],
    description: '',
  },
  {
    name: 'RIVET_NO_CROSS_SESSION',
    defaultHint: '',
    files: ['agent/cross-session-memory-config.ts', 'agent/loop.ts', 'agent/__tests__/cross-session-killswitch.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_NO_EMBEDDINGS',
    defaultHint: '',
    files: ['search/embedding-provider.ts'],
    description: '',
  },
  {
    name: 'RIVET_NO_SYSTEM_PROXY',
    defaultHint: '',
    files: ['tui/__tests__/updater.test.ts', 'tools/net/proxy-resolver.ts'],
    description: '',
  },
  {
    name: 'RIVET_NO_UPDATE_CHECK',
    defaultHint: '',
    files: ['main.ts'],
    description: '',
  },
  {
    name: 'RIVET_NOTIFY_BELL',
    defaultHint: '',
    files: ['tui/engine/app.ts'],
    description: '',
  },
  {
    name: 'RIVET_OAUTH_PORT',
    defaultHint: '',
    files: ['mcp/oauth/connector.ts'],
    description: '',
  },
  {
    name: 'RIVET_OAUTH_TIMEOUT',
    defaultHint: '\'\'',
    files: ['auth/oauth-auth.ts'],
    description: '',
  },
  {
    name: 'RIVET_ORCHESTRATION_HINT',
    defaultHint: '',
    files: ['main.ts'],
    description: '',
  },
  {
    name: 'RIVET_OUTPUT_SANITIZE',
    defaultHint: '',
    files: ['agent/tool-execution.ts'],
    description: '',
  },
  {
    name: 'RIVET_PAL',
    defaultHint: '',
    files: ['tools/attack-case.ts', 'agent/hooks/problem-attack-hook.ts'],
    description: '',
  },
  {
    name: 'RIVET_PARENT_PID',
    defaultHint: '',
    files: ['server/serve.ts', 'server/__tests__/parent-watchdog.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_PLAN_CONSTRAINTS',
    defaultHint: '',
    files: ['agent/plan-constraints.ts', 'agent/__tests__/plan-constraints.test.ts'],
    description: '设为 0 关闭计划约束自动注入（D8 L2），resolvePlanConstraints 恒返回 []',
  },
  {
    name: 'RIVET_PLAN_MODE_SUGGEST',
    defaultHint: '',
    files: ['agent/plan-mode-advisor.ts', 'agent/__tests__/plan-mode-advisor.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_PLAYBOOK_INJECT',
    defaultHint: '',
    files: ['agent/context-injection.ts', 'agent/__tests__/playbook-injection-revival.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_PRO',
    defaultHint: '',
    files: ['server/__tests__/recordings-distill-route.test.ts', 'config/pro-license.ts', 'config/__tests__/pro-license.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_PROBE_DISCIPLINE',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_PROBE_TRACKING',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_PROFILE',
    defaultHint: '',
    files: ['main.ts', 'config/profile.ts', 'config/__tests__/config-watcher.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_PROMPT_PROFILE',
    defaultHint: 'profile',
    files: ['prompt/block-policy.ts', 'prompt/__tests__/block-policy.test.ts', 'config/__tests__/runtime-lean.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_PROMPT_TOOL_DESC',
    defaultHint: 'toolDescriptions',
    files: ['prompt/block-policy.ts'],
    description: '',
  },
  {
    name: 'RIVET_REASONING_SPIRAL_GUARD',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_REGRESSION_BISECT',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_RELIABILITY_OVERRIDE',
    defaultHint: '',
    files: ['agent/loop.ts'],
    description: '',
  },
  {
    name: 'RIVET_RENDER_VERIFY',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts', 'agent/deliver-task.ts'],
    description: '',
  },
  {
    name: 'RIVET_REPO_GRAPH',
    defaultHint: '',
    files: ['bootstrap.ts'],
    description: '',
  },
  {
    name: 'RIVET_RESUME',
    defaultHint: '',
    files: ['bootstrap.ts', 'main.ts'],
    description: '',
  },
  {
    name: 'RIVET_RESUME_ID',
    defaultHint: '',
    files: ['bootstrap.ts', 'main.ts'],
    description: '',
  },
  {
    name: 'RIVET_REVIEW_DISCIPLINE',
    defaultHint: '',
    files: ['config/review-discipline-config.ts'],
    description: '',
  },
  {
    name: 'RIVET_RIPGREP_PATH',
    defaultHint: '',
    files: ['tools/grep.ts'],
    description: '',
  },
  {
    name: 'RIVET_RTK',
    defaultHint: '',
    files: ['tools/bash.ts', 'tools/__tests__/bash.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_SANDBOX',
    defaultHint: '',
    files: ['tools/bash.ts', 'tools/sandbox-profile.ts', 'tools/__tests__/sandbox-profile.test.ts'],
    description: '追加可写根目录，平台分隔符分隔（POSIX 用 :，Windows 用 ;）。与工具链画像、会话授权合并。',
  },
  {
    name: 'RIVET_SANDBOX_WRITABLE',
    defaultHint: '',
    files: ['tools/sandbox-profile.ts'],
    description: '',
  },
  {
    name: 'RIVET_SCOUT_FIREWALL',
    defaultHint: '',
    files: ['config/scout-firewall-config.ts', 'config/__tests__/scout-firewall-config.test.ts', 'agent/__tests__/deliver-task.test.ts'],
    description: '证据防火墙 Phase 2：deliver_task commit 引用未核验 scout 断言时 isError 硬拦，默认关（opt-in）；设 1/true/on 开启，0/false/off 强制关（等价 config agent.scoutEvidenceFirewall）',
  },
  {
    name: 'RIVET_SCRIPT_ITERATION_DETECTOR',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_SEARCH_POD',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_SECURITY_GUIDANCE',
    defaultHint: '',
    files: ['config/security-guidance-config.ts', 'agent/__tests__/create-runtime-hooks.test.ts'],
    description: '安全模式正则告警（层1）总开关，默认开；设 0/false/off/no 关闭（等价 config agent.securityGuidance=false）',
  },
  {
    name: 'RIVET_SERVE_TIMING',
    defaultHint: '',
    files: ['server/serve.ts'],
    description: '',
  },
  {
    name: 'RIVET_SERVER_TOKEN',
    defaultHint: '',
    files: ['server/serve.ts'],
    description: '',
  },
  {
    name: 'RIVET_SESSION_DIR',
    defaultHint: '',
    files: ['server/__tests__/cache-routes.test.ts', 'server/__tests__/handoff-route.test.ts', 'server/__tests__/serve-restore-history.test.ts', 'server/__tests__/session-routes.test.ts', 'prompt/__tests__/frozen-snapshot-persist.test.ts', 'config/paths.ts', 'agent/__tests__/appendix-trace.test.ts', 'agent/__tests__/handoff-persist.test.ts', 'agent/__tests__/loop-factory.test.ts', 'agent/__tests__/persist-integration.test.ts', 'agent/__tests__/session-cd.test.ts', 'agent/__tests__/session-persist-codec.test.ts', 'agent/__tests__/session-persist.test.ts', 'agent/__tests__/speculation-stats-meta.test.ts', 'agent/__tests__/tool-pipeline.test.ts', 'agent/__tests__/worker-session.test.ts', '__tests__/bootstrap.test.ts', '__tests__/switch-agent-session.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_SIDECAR_ENTRY',
    defaultHint: '',
    files: ['server/plugin-api.ts'],
    description: '',
  },
  {
    name: 'RIVET_SKILL_GATE',
    defaultHint: '',
    files: ['agent/skill-gate.ts', 'agent/__tests__/skill-gate.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_SKIP_STAGED_RUNTIME_CHECK',
    defaultHint: '',
    files: ['platform/staged-runtime-guard.ts'],
    description: '',
  },
  {
    name: 'RIVET_STREAM_RESULT_MAX',
    defaultHint: '',
    files: ['stream-json.ts', '__tests__/stream-json.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TDD_GATE',
    defaultHint: '\'\'',
    files: ['agent/tdd-gate.ts', 'agent/__tests__/tdd-gate.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TEST',
    defaultHint: '',
    files: ['agent/coordinator.ts'],
    description: '',
  },
  {
    name: 'RIVET_TEST_CANDIDATE_KEY',
    defaultHint: '',
    files: ['agent/__tests__/candidate-models.test.ts'],
    description: '仅测试用：候选池凭据过滤测试的假 API key 注入点，生产代码不读',
  },
  {
    name: 'RIVET_TEST_ENV_KEY_PROV',
    defaultHint: '',
    files: ['server/__tests__/serve-switch-model.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TEST_GLM_KEY',
    defaultHint: '',
    files: ['__tests__/switch-agent-session.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TEST_PRESENCE_GATE',
    defaultHint: '',
    files: ['agent/test-presence.ts', 'agent/__tests__/deliver-task.test.ts', 'agent/__tests__/test-presence.test.ts', 'agent/__tests__/wave-gate.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TOOL_PRESET',
    defaultHint: '',
    files: ['tools/tool-preset.ts', 'tools/__tests__/tool-preset.test.ts', 'config/__tests__/runtime-lean.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TRUST_PROJECT',
    defaultHint: '',
    files: ['main.ts', 'tools/__tests__/monitor-tool.test.ts', 'tools/__tests__/run-tests-declared.test.ts', 'server/__tests__/hooks-route.test.ts', 'server/__tests__/mcp-server-config.test.ts', 'server/__tests__/serve-agent-config-merge.test.ts', 'server/__tests__/session-manager.test.ts', 'server/__tests__/trust-api.test.ts', 'prompt/__tests__/volatile.test.ts', 'config/__tests__/layered-config.test.ts', 'config/__tests__/project-trust.test.ts', 'config/__tests__/verify-config.test.ts', 'agent/__tests__/typecheck-gate.test.ts', 'agent/__tests__/user-hooks-bridge.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TS_LOAD_TIMEOUT',
    defaultHint: '\'\'',
    files: ['tools/syntax-check.ts'],
    description: 'syntax-check 加载 esbuild 的超时（ms；0/负数回退 3s）',
  },
  {
    name: 'RIVET_TS_PARSE_TIMEOUT',
    defaultHint: '\'\'',
    files: ['tools/syntax-check.ts', 'tools/__tests__/syntax-check.test.ts'],
    description: 'tree-sitter Python 语法校验的加载+解析超时(ms),缺省 5000',
  },
  {
    name: 'RIVET_TSC_FALLBACK_TIMEOUT',
    defaultHint: '\'\'',
    files: ['tools/syntax-check.ts'],
    description: '',
  },
  {
    name: 'RIVET_TUI_HARDWARE_CURSOR',
    defaultHint: '',
    files: ['tui/engine/live-engine.ts', 'tui/engine/__tests__/live-engine.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TURN_BUDGET_WARN',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_TYPECHECK_GATE',
    defaultHint: '',
    files: ['agent/typecheck-gate.ts', 'agent/__tests__/typecheck-gate.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TYPECHECK_REPO_WIDE',
    defaultHint: '',
    files: ['agent/typecheck-gate.ts', 'agent/__tests__/typecheck-gate.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TYPECHECK_SHARE',
    defaultHint: '',
    files: ['lsp/client.ts'],
    description: '',
  },
  {
    name: 'RIVET_VERSION',
    defaultHint: '\'0.0.0-dev\'',
    files: ['server/serve.ts', 'api/provider-catalog.ts'],
    description: '',
  },
  {
    name: 'RIVET_VSW',
    defaultHint: '',
    files: ['bootstrap.ts'],
    description: '',
  },
  {
    name: 'RIVET_WAVE_GATE',
    defaultHint: '',
    files: ['tools/__tests__/plan-task.test.ts', 'agent/wave-gate.ts', 'agent/__tests__/plan-executor.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_WEB_CRAWL',
    defaultHint: '',
    files: ['tools/default-registry.ts'],
    description: '',
  },
  {
    name: 'RIVET_WEB_MAP',
    defaultHint: '',
    files: ['tools/default-registry.ts'],
    description: '',
  },
  {
    name: 'RIVET_WELCOME_ANIM',
    defaultHint: '',
    files: ['main.ts'],
    description: '',
  },
  {
    name: 'RIVET_WELCOME_GREETING',
    defaultHint: '',
    files: ['tui/welcome-greeting.ts', 'tui/__tests__/welcome-greeting.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_WHISPER_BIN',
    defaultHint: '',
    files: ['server/speech-routes.ts', 'server/__tests__/speech-routes.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_WHISPER_FETCH_SCRIPT',
    defaultHint: '',
    files: ['server/speech-routes.ts', 'server/__tests__/speech-routes.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_WHISPER_MODEL',
    defaultHint: '',
    files: ['server/speech-routes.ts', 'server/__tests__/speech-routes.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_WHISPER_PROXY',
    defaultHint: '',
    files: ['server/speech-routes.ts', 'server/__tests__/speech-routes.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_WORKER_BUDGET_HISTORY',
    defaultHint: '',
    files: ['agent/budget-shape.ts', 'agent/__tests__/budget-shape.test.ts'],
    description: '=0 关闭写工预算的历史实际用量地板（同 objective 的 worker_actual 样本不再抬升预算）',
  },
  {
    name: 'RIVET_WORKER_BUDGET_SHAPE',
    defaultHint: '',
    files: ['agent/budget-shape.ts', 'agent/__tests__/budget-shape.test.ts'],
    description: '=0 关闭写工预算的文件形状定价（48 轮/600s flat 默认回归）',
  },
  {
    name: 'RIVET_WORKER_FINALIZE',
    defaultHint: '',
    files: ['agent/coordinator.ts'],
    description: '',
  },
  {
    name: 'RIVET_WORKER_ISOLATION',
    defaultHint: '',
    files: ['agent/worker-process/parent.ts', 'agent/worker-process/__tests__/worker-process.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_WORKER_WRITE_GATE',
    defaultHint: '',
    files: ['agent/worker-write-gate.ts', 'agent/__tests__/hands-session.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_WRAPUP_ANXIETY_GUARD',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_WRITE_OVERWRITE_GUARD',
    defaultHint: '',
    files: ['tools/write-file.ts', 'tools/__tests__/write-file.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_WRITE_PROBE',
    defaultHint: '',
    files: ['context/write-evidence-probe.ts', 'context/__tests__/write-evidence-probe.test.ts'],
    description: '',
  },
]
